spring.application.name=demo
# URL do Banco de dados local usando a porta padrão (5432) do POSTGRESQL, altere o final da URL com o nome do banco local da sua maquina
spring.datasource.url=jdbc:postgresql://localhost:5432/nutri-express 
# Altere o username + password para os configurado em seu pgAdmin4 caso esteja usando um banco local
spring.datasource.username=postgres
spring.datasource.password=Db@Obj.3213
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update