spring.application.name=demo
# URL do Banco de dados local usando a porta padrão (5432) do POSTGRESQL, altere o final da URL com o nome do banco local da sua maquina
spring.datasource.url=jdbc:postgresql://localhost:5432/NOME_DO_SEU_BANCO
# Altere o username + password para os configurado em seu pgAdmin4 caso esteja usando um banco local
spring.datasource.username=SEU_USUARIO
spring.datasource.password=SUA_SENHA
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update