spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/nutri-express
spring.datasource.username=postgres
spring.datasource.password=Db@Obj.3213
spring.datasource.driver-class-name=org.postgresql.Driver
